root = "."
tmp_dir = "tmp"

[build]
cmd = "go run ./cmd/api/main.go"
bin = "tmp/server"
include_ext = ["go"]
exclude_dir = ["tmp", "bin", "vendor", "node_modules"]
delay = 200

[log]
time = true

[screen]
clear_on_rebuild = true
